// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ISEStudio.Infrastructure.Persistence;

#nullable disable

namespace ISEStudio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ISEStudioDbContext))]
    partial class ISEStudioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.AboxProvenanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("AuditEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("extraction");

                    b.Property<string>("ReviewRecord")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AuditEventId")
                        .HasDatabaseName("ix_aboxprov_audit_event_id");

                    b.HasIndex("ChunkId")
                        .HasDatabaseName("ix_aboxprov_chunk_id");

                    b.HasIndex("FactKey")
                        .HasDatabaseName("ix_aboxprov_fact_key");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_aboxprov_job_id");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_aboxprov_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_aboxprov_legacy_id");

                    b.ToTable("aboxprovenance", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<byte[]>("Added")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb");

                    b.Property<string>("Graph")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("GroupId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<byte[]>("Removed")
                        .HasColumnType("bytea");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_auditevent_action");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_auditevent_actor_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_auditevent_created_at");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_auditevent_group_id");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_auditevent_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_auditevent_legacy_id");

                    b.ToTable("auditevent", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.AuthSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_authsession_legacy_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ux_authsession_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_authsession_user_id");

                    b.ToTable("authsession", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.AxiomProvenanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<Guid?>("AuditEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("AxiomKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("extraction");

                    b.Property<string>("ReviewRecord")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AuditEventId")
                        .HasDatabaseName("ix_axiomprov_audit_event_id");

                    b.HasIndex("AxiomKey")
                        .HasDatabaseName("ix_axiomprov_axiom_key");

                    b.HasIndex("ChunkId")
                        .HasDatabaseName("ix_axiomprov_chunk_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_axiomprov_job_id");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_axiomprov_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_axiomprov_legacy_id");

                    b.ToTable("axiomprovenance", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CharEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("CharStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Idx")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokenEstimate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_chunk_document_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_chunk_legacy_id");

                    b.ToTable("chunk", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ConflictEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ctype")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<string>("Resolution")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("error");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("Ctype")
                        .HasDatabaseName("ix_conflict_ctype");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_conflict_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_conflict_legacy_id");

                    b.HasIndex("Signature")
                        .HasDatabaseName("ix_conflict_signature");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_conflict_status");

                    b.ToTable("conflict", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AboxExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChunkCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Ext")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("/");

                    b.Property<Guid?>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Mime")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ParseError")
                        .HasColumnType("text");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending");

                    b.Property<string>("ParserBackend")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset?>("TboxExtractedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TextCharCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ext")
                        .HasDatabaseName("ix_document_ext");

                    b.HasIndex("Folder")
                        .HasDatabaseName("ix_document_folder");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_document_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_document_legacy_id");

                    b.HasIndex("ParseStatus")
                        .HasDatabaseName("ix_document_parse_status");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_document_sha256");

                    b.HasIndex("KnowledgeSystemId", "Sha256")
                        .IsUnique()
                        .HasDatabaseName("ux_document_knowledge_system_id_sha256");

                    b.ToTable("document", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.EntityResolutionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassIri")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Context")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndividualIri")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("SourceChunkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending");

                    b.Property<string>("SurfaceForm")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ClassIri")
                        .HasDatabaseName("ix_er_class_iri");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_er_created_at");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_er_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_er_legacy_id");

                    b.HasIndex("SourceChunkId")
                        .HasDatabaseName("ix_er_source_chunk_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_er_status");

                    b.HasIndex("SurfaceForm")
                        .HasDatabaseName("ix_er_surface_form");

                    b.ToTable("entityresolution", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ExportJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Files")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("nquads");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("OutputDir")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.Property<int>("ProcessedStatements")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("ShardSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100000);

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending");

                    b.Property<int>("TotalStatements")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_exportjob_created_at");

                    b.HasIndex("CreatedById");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_exportjob_knowledge_system_id");

                    b.HasIndex("Layer")
                        .HasDatabaseName("ix_exportjob_layer");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_exportjob_legacy_id");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_exportjob_release_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_exportjob_status");

                    b.ToTable("exportjob", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ExtractionJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssertionsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("AxiomsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.PrimitiveCollection<string>("ChunkIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ClassesAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IndividualsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("tbox");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Log")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<int>("PendingAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Phase")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("");

                    b.Property<int>("ProcessedChunks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PromptSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<int>("PropertiesAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending");

                    b.Property<string>("TerminologyError")
                        .HasColumnType("text");

                    b.Property<int>("TerminologyProposals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TermsAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TermsMapped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalChunks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("UnknownClasses")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_extractionjob_kind");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_extractionjob_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_extractionjob_legacy_id");

                    b.HasIndex("Phase")
                        .HasDatabaseName("ix_extractionjob_phase");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_extractionjob_status");

                    b.ToTable("extractionjob", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.KSGrantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("viewer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_ksgrant_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_ksgrant_legacy_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ksgrant_user_id");

                    b.ToTable("ksgrant", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeApiTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SecretCiphertext")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_kat_created_by");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_kat_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_kat_legacy_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_kat_name");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_kat_token_hash");

                    b.ToTable("knowledgeapitoken", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.KnowledgePromptOverrideEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("PromptKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_kpo_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_kpo_legacy_id");

                    b.HasIndex("PromptKey")
                        .HasDatabaseName("ix_kpo_prompt_key");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("KnowledgeSystemId", "PromptKey")
                        .IsUnique()
                        .HasDatabaseName("ux_kpo_knowledge_system_id_prompt_key");

                    b.ToTable("knowledgepromptoverride", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AxiomCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("BaseIri")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.Property<int>("ClassCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("EmbeddingProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("GraphIri")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("LlmModel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("LlmProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("PropertyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddingProviderId");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_ks_legacy_id");

                    b.HasIndex("LlmProviderId");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_ks_name");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_ks_owner_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_ks_public_id");

                    b.ToTable("knowledgesystem", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.McpUserTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("Scopes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_mcp_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_mcp_legacy_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_mcp_name");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_mcp_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_mcp_user_id");

                    b.ToTable("mcpusertoken", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.OntologyReleaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Manifest")
                        .HasColumnType("jsonb");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedById")
                        .HasColumnType("uuid");

                    b.Property<string>("PublishedByName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewedByName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("SnapshotDir")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_release_created_at");

                    b.HasIndex("CreatedById");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_release_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_release_legacy_id");

                    b.HasIndex("PublishedById");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_release_status");

                    b.HasIndex("Version")
                        .HasDatabaseName("ix_release_version");

                    b.HasIndex("KnowledgeSystemId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_release_knowledge_system_id_version");

                    b.ToTable("ontologyrelease", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasDefaultValue("");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasDefaultValue("");

                    b.Property<int>("ConcurrencyLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("llm");

                    b.Property<bool?>("LastTestOk")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastTestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_provider_legacy_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_provider_name");

                    b.ToTable("provider", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ReleaseDeploymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AboxGraphIri")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<int>("ProvenanceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("StatementCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("provisioning");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TboxGraphIri")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.Property<string>("VocabularyGraphIri")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_deployment_created_at");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_deployment_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_deployment_legacy_id");

                    b.HasIndex("ReleaseId")
                        .IsUnique()
                        .HasDatabaseName("ux_deployment_release_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_deployment_status");

                    b.ToTable("releasedeployment", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ReleaseStatementProvenanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatementKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_rsp_knowledge_system_id");

                    b.HasIndex("Layer")
                        .HasDatabaseName("ix_rsp_layer");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_rsp_legacy_id");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_rsp_release_id");

                    b.HasIndex("StatementKey")
                        .HasDatabaseName("ix_rsp_statement_key");

                    b.ToTable("releasestatementprovenance", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.SystemConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("EmbeddingProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExtractModel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("ExtractionConcurrency")
                        .HasColumnType("integer");

                    b.Property<long>("LegacyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("legacy_id");

                    b.Property<Guid?>("LlmProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmbeddingProviderId");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_systemconfig_legacy_id");

                    b.HasIndex("LlmProviderId");

                    b.ToTable("systemconfig", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.TboxReconciliationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Candidates")
                        .HasColumnType("jsonb");

                    b.Property<string>("Choice")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("");

                    b.Property<string>("ChosenLabel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("PropertyIri")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PropertyLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tboxr_created_at");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_tboxr_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_tboxr_legacy_id");

                    b.HasIndex("PropertyLabel")
                        .HasDatabaseName("ix_tboxr_property_label");

                    b.HasIndex("Slot")
                        .HasDatabaseName("ix_tboxr_slot");

                    b.ToTable("tboxreconciliation", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.TermProposalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evidence")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ExtractionJobId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<string>("ProposedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("terminology-agent");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SourceChunkIds")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("pending");

                    b.Property<string>("TargetIri")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Term")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_tp_action");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tp_created_at");

                    b.HasIndex("ExtractionJobId")
                        .HasDatabaseName("ix_tp_extraction_job_id");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_tp_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_tp_legacy_id");

                    b.HasIndex("Signature")
                        .HasDatabaseName("ix_tp_signature");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tp_status");

                    b.HasIndex("TargetIri")
                        .HasDatabaseName("ix_tp_target_iri");

                    b.HasIndex("Term")
                        .HasDatabaseName("ix_tp_term");

                    b.ToTable("termproposal", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_legacy_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ValidationDecisionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KnowledgeSystemId")
                        .HasColumnType("uuid");

                    b.Property<long>("LegacyId")
                        .HasColumnType("bigint")
                        .HasColumnName("legacy_id");

                    b.Property<string>("PropertyIri")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PropertyLabel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("XsdType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_vd_created_at");

                    b.HasIndex("KnowledgeSystemId")
                        .HasDatabaseName("ix_vd_knowledge_system_id");

                    b.HasIndex("LegacyId")
                        .IsUnique()
                        .HasDatabaseName("ux_vd_legacy_id");

                    b.HasIndex("PropertyIri")
                        .HasDatabaseName("ix_vd_property_iri");

                    b.HasIndex("PropertyLabel")
                        .HasDatabaseName("ix_vd_property_label");

                    b.ToTable("validationdecision", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.AboxProvenanceEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.AuditEventEntity", null)
                        .WithMany()
                        .HasForeignKey("AuditEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.ChunkEntity", null)
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.ExtractionJobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.AuthSessionEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.AxiomProvenanceEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.AuditEventEntity", null)
                        .WithMany()
                        .HasForeignKey("AuditEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.ChunkEntity", null)
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.ExtractionJobEntity", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ChunkEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.DocumentEntity", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ConflictEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.DocumentEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.EntityResolutionEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.ChunkEntity", null)
                        .WithMany()
                        .HasForeignKey("SourceChunkId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ExportJobEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.OntologyReleaseEntity", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ExtractionJobEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.KSGrantEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeApiTokenEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", "KnowledgeSystem")
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KnowledgeSystem");
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.KnowledgePromptOverrideEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.ProviderEntity", null)
                        .WithMany()
                        .HasForeignKey("EmbeddingProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.ProviderEntity", null)
                        .WithMany()
                        .HasForeignKey("LlmProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.McpUserTokenEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", "KnowledgeSystem")
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KnowledgeSystem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.OntologyReleaseEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("PublishedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ReleaseDeploymentEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.OntologyReleaseEntity", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ReleaseStatementProvenanceEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.OntologyReleaseEntity", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.SystemConfigEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.ProviderEntity", null)
                        .WithMany()
                        .HasForeignKey("EmbeddingProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.ProviderEntity", null)
                        .WithMany()
                        .HasForeignKey("LlmProviderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.TboxReconciliationEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.TermProposalEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.ExtractionJobEntity", null)
                        .WithMany()
                        .HasForeignKey("ExtractionJobId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ISEStudio.Infrastructure.Persistence.Entities.ValidationDecisionEntity", b =>
                {
                    b.HasOne("ISEStudio.Infrastructure.Persistence.Entities.KnowledgeSystemEntity", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
