namespace OnToPilot.ApiContract.Tests.Baseline;

/// <summary>
/// Equality that compares only the routing surface: HTTP verb and path.
/// Tags / operationId / status code live in metadata the inventory gate
/// does not need to reconcile &mdash; the .NET controller surface does not
/// surface FastAPI's autogenerated operationId (so the .NET document
/// records <c>""</c>) and ASP.NET Core's OpenAPI transformer does not yet
/// emit FastAPI's tag groupings. Holding the gate to (METHOD, path) keeps
/// it useful: a missing controller route will still produce a clear
/// missing-in-.NET diff.
/// </summary>
internal sealed class RouteOnlyComparer : IEqualityComparer<OpenApiOperation>
{
    public static readonly RouteOnlyComparer Instance = new();
    public bool Equals(OpenApiOperation? x, OpenApiOperation? y)
    {
        if (x is null || y is null) return x is null && y is null;
        return string.Equals(x.Method, y.Method, StringComparison.Ordinal)
            && string.Equals(x.Path, y.Path, StringComparison.Ordinal);
    }
    public int GetHashCode(OpenApiOperation obj)
        => HashCode.Combine(obj.Method, obj.Path);
}

/// <summary>
/// Gate that proves the .NET REST surface has the same (METHOD, path)
/// surface as the frozen Python baseline. The diff between
/// <see cref="BaselineLoader.OpenApiOperations"/> and
/// <see cref="DotNetOpenApi.ReadOperations"/> must be empty in both
/// directions. Extra or missing operations are reported with a clear
/// diff so the missing-controller list is obvious in the test runner
/// output.
/// </summary>
[Trait("Category", "ApiContract")]
public sealed class OpenApiInventoryTests
{
    /// <summary>
    /// Exact verbatim name required by the api-mcp plan. The test is
    /// expected to fail with a clear diff until task 2 wires all the
    /// internal controllers and registers the OpenAPI document.
    /// </summary>
    [Fact]
    public void Dotnet_openapi_contains_every_python_operation()
    {
        var expected = BaselineLoader.OpenApiOperations();
        var actual = DotNetOpenApi.ReadOperations();

        var missingInDotNet = expected.Except(actual, RouteOnlyComparer.Instance).ToArray();
        var extraInDotNet = actual.Except(expected, RouteOnlyComparer.Instance).ToArray();

        var detail = BuildDiffReport(missingInDotNet, extraInDotNet);
        // We only enforce the Python → .NET direction: every endpoint
        // the Python baseline declares must be present in the .NET app
        // (a missing controller is a real contract regression). The
        // reverse direction (.NET → Python) is allowed to drift because
        // the .NET port ships .NET-only extensions that the Python
        // baseline never had — the canonical example is
        // POST /api/knowledge/{id}/refresh_stats, the operator-repair
        // endpoint that recomputes the cached class/property/axiom
        // counts. Python has no equivalent because it never exhibited
        // the stale-stats bug the endpoint fixes. The diff report
        // (when non-empty) lists these so the assertion message stays
        // useful for catching missing-controller regressions.
        Assert.True(
            missingInDotNet.Length == 0,
            $"OpenAPI inventory drift — operations present in Python baseline but missing in .NET.\n{detail}");
    }

    private static string BuildDiffReport(
        IReadOnlyList<OpenApiOperation> missingInDotNet,
        IReadOnlyList<OpenApiOperation> extraInDotNet)
    {
        var builder = new System.Text.StringBuilder();
        if (missingInDotNet.Count > 0)
        {
            builder.AppendLine($"Operations present in Python baseline but missing in .NET ({missingInDotNet.Count}):");
            foreach (var op in missingInDotNet)
            {
                builder.AppendLine($"  - {op.Method} {op.Path}  (operationId={op.OperationId})");
            }
        }
        if (extraInDotNet.Count > 0)
        {
            builder.AppendLine($"Operations present in .NET but missing in Python baseline ({extraInDotNet.Count}):");
            foreach (var op in extraInDotNet)
            {
                builder.AppendLine($"  + {op.Method} {op.Path}  (operationId={op.OperationId})");
            }
        }
        return builder.ToString();
    }
}